Update release checklist: need to update docs and demo sites.
plone/buildout.coredev pull request #858
Opened 2023-04-27 14:14 UTC by mauritsvanrees

2023-04-27 14:15 UTC, mauritsvanrees commented
No Jenkins jobs needed for this PR.

Just looking for feedback: if the involved people want a different text here to clarify what should be done, this is a good time to speak up.

2023-04-27 19:34 UTC, fredvd approved these changes
LGTM.  Seems something we could ‘officialise’ as release team tasks.

 Allthough if you look at it practically the release team is a virtual team where the release managers, ci-team, ai-team, docs, and training team members coordinate the subtasks from their team domain for every release.

2023-04-27 22:30 UTC, stevepiercy requested changes
Some grammar fixes and explicit details to include `PLONE_BACKEND_MINOR_VERSION` as well as needed.

2023-04-27 22:30 UTC, stevepiercy commented on release/checklist.md
> +- [ ] Notify Erico Andrei and/or Fred van Dijk, for example the `#release-team` Discord channel, that there is a new release, so they can create Docker images then.  Sample changes: [`README.md`](htt
```suggestion
- [ ] Notify Érico Andrei and/or Fred van Dijk in the `#release-team` Discord channel that there is a new release. They will create Docker images. Examples of changes: [`README.md`](https://github.com/plone/plone-backend/commit/0e3ce3c190677c04874ebed6b527a845cc075bca) and [`version.txt`](https://github.com/plone/plone-backend/commit/cee1e0bbb17ed24c64cd42342929a020346e1da1).
```

2023-04-27 22:30 UTC, stevepiercy commented on release/checklist.md
> +- [ ] Update Plone version in documentation.  Ask Steve Piercy or do it yourself.  Here is a [sample PR](https://github.com/plone/documentation/pull/1492/files).
```suggestion
- [ ] In [`plone/documentation`'s `conf.py`](https://github.com/plone/documentation/blob/6-dev/docs/conf.py#L325-L326), update `PLONE_BACKEND_PATCH_VERSION` and `PLONE_BACKEND_MINOR_VERSION` as needed. Ask Steve Piercy or do it yourself. Here is a [sample PR](https://github.com/plone/documentation/pull/1492/files).
```

2023-04-28 09:45 UTC, stevepiercy approved these changes
Thank you!

2023-04-28 13:05 UTC, merged