Bootstrap 5.3 for Plone 6.0.x
plone/buildout.coredev pull request #864
Opened 2023-06-05 09:42 UTC by petschki

2023-06-05 09:49 UTC, petschki commented
@gforcada can a coredev PR be tested with Jenkins PR ?

2023-06-05 10:03 UTC, ale-rt commented
I think you need to login to jenkins and use this form: https://jenkins.plone.org/job/pull-request-6.0-3.11/build?delay=0sec

Just paste the URL of the PR and click build.

2023-06-05 10:05 UTC, petschki commented
@ale-rt I tried that here https://jenkins.plone.org/job/pull-request-6.0-3.8/2731/ but the pulled revision of the buildout is the latest from `6.0` branch and not this PR unfortunately...

2023-06-05 10:16 UTC, petschki commented
I'm not sure about this log either: `PR 6.0-py3.8` says it uses `python3.9` ? https://jenkins.plone.org/job/pull-request-6.0-3.8/2731/consoleFull

<img width="1411" alt="Bildschirmfoto 2023-06-05 um 12 15 26" src="https://github.com/plone/buildout.coredev/assets/511761/45a0196f-498a-4315-be26-df7fcd42cec0">

2023-06-06 07:37 UTC, thet requested changes
IIRC we discussed with @mauritsvanrees that Bootstrap 5.3 should go into Plone 6.1.
Otherwise we wouldn't have needed all the Plone 6.1 related branches.
IMO this should not be merged into the 6.0 coredev branch but be kept for 6.1. Which I hope will manifest soon.

What's you opinion on this @mauritsvanrees ?

2023-06-06 07:54 UTC, gforcada commented
@petschki yes, as @ale-rt mentioned one should be able to use PR jobs for testing buildout.coredev branches, I think that even if they are remote branches it does work, but fails at reporting the status back at GitHub (I think)

As for the python 3.9: yes and no 😄 

The `build` steps on a PR jenkins jobs are like that:

- ping back GitHub that a build has started (so you see the spinning dot on the PRs)
- run the tests
- report the status back on GitHub

The first and last steps are common to all PR jobs, and to make it easier to manage them a separate virtualenv (as some dependencies are needed) is created for them, but that python version is not used for running the tests 🍀 

If you scroll a bit more you will see:

```
/home/jenkins/workspace/pull-request-6.0-3.8/venv/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
```

All warnings, when already running the tests, are actually pointing to `venv/lib/python3.8` 😄 

All jobs configuration and scripts are found in: https://github.com/plone/jenkins.plone.org/tree/master/jobs I'm happy to review and improve them with any feedback you have 😉

2023-06-06 07:58 UTC, petschki commented
@thet you remember correctly - this was at Alpine City Sprint. But during developing and impoving the classic-ui packages since then, we already did all the features and bugfixes twice for both BS versions. The only difference is, that BS 5.3 improves the CSS color variable management implementing `color modes` with a default set for the `dark` mode. So from my point of view it would make classic-ui frontend developers life easier if we move on and concentrate on one branch only.

Affected core packages:
- `@plone/mockup`: `5.0.x` -> `5.1.x`
- `plone.staticresources`: `2.0.x` -> `2.1.x`
- `plonetheme.barceloneta: `3.0.x` -> `3.1.x`
- `@plone/plonetheme-barceloneta-base`: `3.0.x` -> `3.1.x`

2023-06-06 08:04 UTC, petschki commented
@gforcada thanks for the python version insights.

Regarding PR jobs for coredev, I think the jenkins logic is not yet capable of testing coredev PRs... if I look at the current job for this PR, it first says, that the revision `58846b13ac9180f2c47f7b7e1d6dd6006716f509` is checked out, and this is the latest revision of `6.0` and not this revision here (the last commit msg also shows this).

https://jenkins.plone.org/job/pull-request-6.0-3.11/666/console

<img width="1252" alt="Bildschirmfoto 2023-06-06 um 10 00 59" src="https://github.com/plone/buildout.coredev/assets/511761/2a24aaa8-10c3-4fb3-9dca-3d36363ed471">

2023-06-06 08:09 UTC, petschki commented
@gforcada ups ... reading console log further please forget my doubts ... there's the info, that the branch was switched:

<img width="914" alt="Bildschirmfoto 2023-06-06 um 10 08 51" src="https://github.com/plone/buildout.coredev/assets/511761/7607a73c-d400-4a90-9f43-341372c958cd">

sorry 🫣

2023-06-06 17:30 UTC, thet approved these changes
@petschki you know what you're doing, maintaining multiple branches is a pain and the mentioned master branches actually do not break anything but only improve.
Approved.

2023-06-09 11:02 UTC, mauritsvanrees commented
I am okay with this in principle.  It was good to have separate branches while Bootstrap 5.3 was still in alpha.  But it is final now, and is only a feature release: nothing should break by using it.

But I wanted to try it out with a custom theme, and this failed for me.  I created an issue: https://github.com/plone/plonetheme.barceloneta/issues/335
A fresh theme based on the "old" Barceloneta fails as well now though.  So we may need some upgrade documentation, but this is true for the old version as well.
That should be fixed.

Also, I saw that the latest Barceloneta tag on npm is still an alpha version: `3.1.0-alpha.1`.  This should be 3.1.3.

I plan to do a Plone 6.0.6 release this month of course.  But I want to skip July, and do 6.0.7 at the end of August.  So we could also say: keep using the older branches for a few weeks longer, and use the new branches once Plone 6.0.6 is out. Then we have two months to catch bugs in coredev.  Does that sound okay?

2023-06-09 12:41 UTC, mauritsvanrees commented
Apart from my remark about a custom theme, I tried it out in three client projects, two of them with Mosaic, and all seems fine.

2023-06-16 10:29 UTC, mauritsvanrees commented
@jenkins-plone-org please run jobs

2023-06-21 09:19 UTC, mauritsvanrees commented on versions-ecosystem.cfg
> +plone.app.standardtiles = 3.1.1
There should be no reason to downgrade plone.app.standardtiles.  I guess this was an accidental change, or it went wrong with some merges.

```suggestion
plone.app.standardtiles = 3.1.2
```

2023-06-21 09:21 UTC, petschki commented
IIRC `p.a.standardtiles` got a release after creating this PR ... thanks for updating!

2023-06-21 09:25 UTC, mauritsvanrees commented
@petschki I went ahead and rebased this branch on 6.0 and force pushed, to get all the latest changes in, and keep just one commit.

@jenkins-plone-org please run jobs

2023-06-21 09:29 UTC, mauritsvanrees commented
For those interested, there is a first Classic UI Team meeting today at 1100 UTC (1.5 hours from now) in Discord in the classic-ui channel.
We can briefly discuss there if this can be merged.

2023-06-21 11:55 UTC, merged